// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateJob(arg1:main.Job):Promise<number>;

export function DeleteJob(arg1:number):Promise<void>;

export function GetAllJobs():Promise<Array<main.Job>>;

export function GetJobByID(arg1:number):Promise<main.Job>;

export function Greet(arg1:string):Promise<string>;

export function RunJobNow(arg1:number):Promise<void>;

export function UpdateJob(arg1:main.Job):Promise<void>;
